version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: make startup
    volumes:
      - static_volume:/home/app/web/static/
      - type: bind
        source: local_storage
        target: /home/app/web/media:Z
    expose:
      - 8000
    container_name: fruit_shop
    env_file:
      - ./.env
    depends_on:
      - db
      - daphne
  daphne:
    build:
      context: ./
    image: daphne:test
    ports:
      - "8080:8080"
      - "8000:8000"
    container_name: daphne_server
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static/
      - type: bind
        source: local_storage
        target: /home/app/web/media:Z
  db:
    image: postgres:14.5-alpine
    volumes:
      - local_storage:/var/lib/postgresql/data:Z
    env_file:
      - ./.env.db
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    restart: always
  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -Q warehouse,celery
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env
    depends_on:
      - celery


volumes:
  cache:
  static_volume:
  local_storage:

