# Generated by Django 4.1.4 on 2022-12-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop', '0003_transaction_auto_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_operation', to='fruitshop.transaction'),
        ),
    ]
