# Generated by Django 4.1.4 on 2022-12-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshop', '0004_product_last_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.PositiveIntegerField(),
        ),
    ]
